version: "3.9"

services:
  quickwit:
    image: quickwit/quickwit:latest
    platform: linux/amd64
    ports:
      - "7280:7280"
    command: run
    volumes:
      - quickwit-data:/quickwit/qwdata

  quickwit-init:
    image: curlimages/curl:latest
    depends_on:
      - quickwit
    volumes:
      - ./index-config.yaml:/index-config.yaml
    entrypoint: >
      sh -c "
      sleep 10 &&
      curl -X POST http://quickwit:7280/api/v1/indexes
      -H 'Content-Type: application/yaml'
      --data-binary @/index-config.yaml
      "
  fluent-bit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./logs:/app/logs:delegated
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/quickwit-oss/quickwit-datasource/releases/download/v0.3.1/quickwit-quickwit-datasource-0.3.1.zip;quickwit-quickwit-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - quickwit
volumes:
  quickwit-data: