[SERVICE]
    Flush        5
    Daemon       off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name   tail
    Path   /app/logs/app.log
    Tag    myapp
    Parser json
    Refresh_Interval 5

[OUTPUT]
    Name          http
    Match         *
    Host          quickwit
    Port          7280
    URI           /api/v1/stackoverflow/ingest
    Format        json_lines
    Header        Content-Type application/json
    json_date_key creationDate
    json_date_format iso8601