version: 0.7

index_id: app-logs

doc_mapping:
  mode: dynamic
  field_mappings:
    - name: msg
      type: text
      stored: true
    - name: status
      type: i64
      fast: true # for search status: >=400
    - name: method
      type: text
      fast: true
    - name: path
      type: text
      tokenizer: default
    - name: request_id
      type: text
      fast: true # Search by ID to view only one person.
    - name: latency
      type: i64 # Stored in nanoseconds by Zap.
      fast: true
    - name: timestamp
      type: datetime
      fast: true
      input_formats: [rfc3339]
  timestamp_field: timestamp

search_settings:
  default_search_fields:
    - msg
    - path
    - request_id

indexing_settings:
  commit_timeout_secs: 30
